GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVrbzMzQGdtYWlsLmNvbSIsImV4cCI6MTY2NTI4NzQ4MSwiaWQiOjMsImlzcyI6InF3ZXJ0eSJ9.KWTn4RwLl7DWgGc0z5ZBnSt2K31ygkKqLnssNBZ2Bsg
###
POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "eko33@gmail.com",
    "password": "12333678"
}